sccn/liblsl

- include/lsl_c.h
- include/lsl_cpp.h
- src/lsl_continuous_resolver_c.cpp
- src/lsl_freefuncs_c.cpp
- src/lsl_inlet_c.cpp
- src/lsl_outlet_c.cpp
- src/lsl_streaminfo_c.cpp
- src/lsl_xml_element_c.cpp
- src/sample.h
- src/stream_outlet_impl.h
This PR picks up 322b5244e1faf9d77b42c0f10944523db0d74dab by @cboulay (reverted because the const qualifiers caused the function names to be mangled and therefore not found when using C linkage) and adds the const qualifiers where needed (i.e. before most pointers to read-only buffers) and marks functions in `*_c.cpp` files as `extern "C"` so the names don't get mangled.
> Declare const parameters as const

- CMakeLists.txt
- lslboost/CMakeLists.txt
With the manylinux builds we pass the linker options via the command line so we don't need the build option any more (commit 1); link MinGW libraries to lslboost, not liblsl (commit 2; #14)
> Some minor CMakeLists.txt cleanups

- .artifactignore
- azure-pipelines.yml
- build_manylinux.sh
- ci/azure_build_steps.yml
I set up a basic build for all three target platforms, anaconda on Linux and manylinux via docker on Azure Pipelines and so far I like it. It has a lot of rough edges concerning artifact deployment (no wildcards), cpack is broken on Windows and conda on Windows / macOS but sooner or later this'll work and we can get a nice badge.
> Set up CI with Azure Pipelines

- CMakeLists.txt
- examples/CMakeLists.txt
- examples/GetAllStreams.cpp
- examples/GetFullinfo.cpp
- examples/GetTimeCorrection.cpp
- examples/HandleMetaData.cpp
- examples/HandleMetaDataC.c
- examples/LICENSE.txt
- examples/README.md
- examples/ReceiveData.cpp
- examples/ReceiveDataC.c
- examples/ReceiveDataInChunks.cpp
- examples/ReceiveDataSimple.cpp
- examples/ReceiveStringMarkers.cpp
- examples/ReceiveStringMarkersC.c
- examples/SendData.cpp
- examples/SendDataC.c
- examples/SendDataInChunks.cpp
- examples/SendDataSimple.cpp
- examples/SendMultipleStreams.cpp
- examples/SendStringMarkers.cpp
- examples/SendStringMarkersC.c
- examples/TestSyncWithoutData.cpp
Discussion is in https://github.com/sccn/labstreaminglayer/issues/37
> Re-add examples

- examples/CMakeLists.txt
- examples/Findliblsl.cmake
This restores the ability to build the examples on their own, without rebuilding all of liblsl by running CMake from the examples folder, either passing `LSL_INSTALL_ROOT` as option or looking for a precompiled liblsl in the default install location.
> CMake: Allow examples to be built independently from liblsl

- CMakeLists.txt
See #47 
Whether or not this gets merged, we at least need the following modification:
```
target_include_directories(lsl
PUBLIC
$<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/include>
$<INSTALL_INTERFACE:include>
)
```
> Rename export to LSLConfig; Define include for installed target

- CMakeLists.txt
- cmake/LSLCMake.cmake
- cmake/LSLConfig.cmake
For #47, put the exported targets into a separate cmake file that gets included alongside the `LSLCMake.cmake` helper functions by `find_package`.
Suggested usage in apps:
```
find_package(LSL 1.13.0 REQUIRED
HINTS ${LSL_INSTALL_ROOT}
"${CMAKE_CURRENT_LIST_DIR}/../../LSL/liblsl/build/"
"${CMAKE_CURRENT_LIST_DIR}/../../LSL/liblsl/build/install"
PATH_SUFFIXES share/LSL
)
```
Tested:
> CMake: add LSLCMake functions to exported configuration

- include/lsl_c.h
- include/lsl_cpp.h
- src/data_receiver.cpp
- src/legacy/legacy_abi.cpp
- src/legacy/legacy_abi.h
- src/lsl_inlet_c.cpp
- src/lsl_outlet_c.cpp
- src/stream_inlet_impl.h
- src/stream_outlet_impl.h
- testing/DataType.cpp
This PR changes user facing integer types to have a well defined size, mostly because types like "long" can be either int32 or int64, depending on OS, compiler and target arch pointer size. It also changes buffer sizes to uint32, because 32 bit clients can't handle more than that and we need 64 and 32 bit clients to be compatible to each other.
This breaks the ABI, so we shouldn't merge this for 1.13.
See also: https://github.com/sccn/lsl_archived/issues/165, https://github.com/sccn/lsl_archived/pull/320
> Use well defined integer sizes

- .github/workflows/cppcmake.yml
- include/lsl_cpp.h
- testing/CMakeLists.txt
- testing/DataType.cpp
- testing/helpers.h
- testing/move.cpp
- testing/timesync.cpp
For compilers with enabled C++11 support, this adds move constructors to the header classes.
This allows passing objects to be passed into classes while ensuring that the underlying objects are deleted when they go out of scope.
Example:
``` cpp
struct Streampair {
lsl::stream_outlet out_;
lsl::stream_inlet in_;
Streampair(lsl::stream_outlet &&out, lsl::stream_inlet &&in)
: out_(std::move(out)), in_(std::move(in)) {}
};
static Streampair create_streampair(const lsl::stream_info &info) {
lsl::stream_outlet out(info);
auto found_stream_info(lsl::resolve_stream("name", info.name(), 1, 2.0));
if (found_stream_info.empty()) throw std::runtime_error("outlet not found");
lsl::stream_inlet in(found_stream_info[0]);
in.open_stream(2);
out.wait_for_consumers(2);
return Streampair(std::move(out), …
```
> Add optional move support to C++ API types

- src/stream_info_impl.cpp
- src/stream_info_impl.h
- testing/CMakeLists.txt
- testing/streaminfo.cpp
Boost.bimap is a bit heavy for a query LRU cache, replacing it with a std::unordered map reduces peak compilation memory usage and debug symbol size by ~10%.
This also adds unit tests for (in-)valid XPath expressions and small optional benchmarks (`LSL_BENCHMARKS`).
Note about speed: a typical XPath expression on a huge XML stream info takes about 2us, a cached query lookup ~0.3us and 1000 cache lookups with automatic pruning of the cache about 2us.
```
trivial query                                             100            23     5.4878 ms 
2.463 us      2.427 us      2.522 us 
228 ns        154 ns        325 ns 
complicated query                                         100             1    130.242 ms 
1.29732 ms    1.28074 ms    1.32216 ms 
101.818 us     76.011 us    165.859 us …
```
> Replace boost.bimap with std::unordered_map

- include/lsl_cpp.h
- src/lsl_resolver_c.cpp
- src/resolver_impl.cpp
- src/resolver_impl.h
- testing/discovery.cpp
At the moment, resolving streams with an invalid query silently fails (i.e. no streams are found).
This PR checks the query and throws an exception on failure before even sending the stream query packets.
> Raise an error when attempting stream resolution with an malformed query

- CMakeLists.txt
- cmake/LSLCMake.cmake
Calculate the MacOS bundle path only once, copy liblsl for Qt-apps, fix the macdeployqt call and show the output in case of an error.
> Fix MacOS Qt deployment

- .travis.yml
- CMakeLists.txt
- include/lsl/common.h
- src/buildinfo.cpp
- src/common.cpp
- standalone_compilation_linux.sh
- testing/CMakeLists.txt
- testing/catch_main.cpp
Add a separate source file with build information to the lsl and lsl-static targets so the XCode generator is happy again.
> Build object target with XCode again

- CMakeLists.txt
- src/resolve_attempt_udp.cpp
- src/resolver_impl.cpp
- src/tcp_server.cpp
- src/udp_server.cpp
Our oldest compiler (RHEL 5, GCC 4.7 for manylinux1) only has full support for C++11, but partial support for lambda initializers (e.g. `[shared_this = shared_from_this()]() { shared_this->do_cancel(); }`) so we should use it. Also avoid implicit `this` in closures when we have a `shared_ptr` pointing to the object.
> Lambda initializers

- src/common.cpp
Hello,
Using python bindings I noticed that I could not properly set a custom handler for SIGINT due to LSL's Loguru catching all signals (e.g. "Loguru caught a signal: SIGINT"), bypassing any other handler. Part of the problem lies I think in how C/C++ code sometimes takes precedence over python during execution when it comes to signals; since there is a thread always executing some LSL code in the background once an inlet is created, I cannot gracefully exit my program when users hit Ctrl-C (among other use cases).
Anyway, I wanted to disable Loguru, and... I could not do it. It appears that the flag `LOGURU_DEBUG_LOGGING` used in `common.cpp` to init Loguru is always set. Indeed, in `loguru.hpp` there is this piece of code:
```
#ifndef LOGURU_DEBUG_LOGGING
#ifndef NDEBUG
#define …
```
> Fixing flag to properly enable/disable loguru

- include/lsl/common.h
The original issue is in #83. Basically, the API has several enums that were passed as 4 byte wide parameters to functions. The C# bindings assumed the enums were single bytes, but the 3 bytes padding before the next parameter made it (mostly) work on little endian architectures.
This PR prevents the compiler from reserving a single byte for the enums and aborts compilation with a helpful error message (on most modern compilers) or at least an error with a line number and explanation on older compilers.
> Ensure enums are 4 bytes wide as implicitly assumed in previous versions

- include/lsl/common.h
- include/lsl_cpp.h
- src/common.cpp
- src/common.h
- src/lsl_c_api_helpers.hpp
- src/lsl_inlet_c.cpp
- src/lsl_outlet_c.cpp
- src/lsl_resolver_c.cpp
- src/lsl_streaminfo_c.cpp
- testing/CMakeLists.txt
- testing/test_ext_streaminfo.cpp
Let's take a simple example:
```
std::vector<std::string> formats = {"", "float32", "float64", "string", "int32", "int16", "int8", "int64"};
std::string format = "double64";
// convert the string to the format index
int fmt = std::distance(formats.begin(), std::find(formats.begin(), formats.end(), format);
try {
lsl::stream_info info(streamname, "EEG", 1, 500, fmt);
} catch(..) { std::cout << "Error!" << std::endl; return; }
std::cout << info.created_at() << std::endl;
```
On a first glance, this should print the time the stream_info was created at.
On a second glance, the format is called `float64`, not `double64` so an exception should be thrown and the function should return.
In reality, a `lsl::stream_info` object is created, but the internal pointer is set to 0 so the call to …
> Improve error handling

- .github/workflows/cppcmake.yml
Starting with Ubuntu 20.04, the `libpugixml-dev` package ships with a CMake config and if there's one thing distributors love it's packages not bundling everything they use. This builds require `libpugixml` to be installed, but the deb package lists it explicitely:
```
$ dpkg -I liblsl-1.14.0-focal_amd64.deb 
neues Debian-Paket, Version 2.0.
Architecture: amd64
Depends: liblsl (= 1.14.0-focal), libc6 (>= 2.29), libgcc-s1 (>= 3.0), libpugixml1v5 (>= 1.6), libstdc++6 (>= 6)
Description: Labstreaminglayer C/C++ library
```
> CI: Build against system pugixml on Ubuntu 20.04

- CMakeLists.txt
Inspired by https://github.com/xdf-modules/libxdf/pull/32.
Basically, the proposed installation of the CMake config in `lib/cmake/LSL` is better in almost any way:
1. it allows side-by-side installations of 32 and 64 bit libraries
2. it's a path search for by default in `find_package()` so no `PATH_SUFFIXES` is needed
3. it makes distribution maintainers like us :-)
> CMake: Change CMake config install dir

- src/lsl_inlet_c.cpp
(this is a dup of #121, rebased on master after some CI fixes)
Very low rate streams combined with smallish max_buflen will give a queue size that gets truncated to 0. The result was a stream that kept disconnecting (at least that's what the log said). Here we + 1 to round up.
For situations where 0 < (nominal_srate() * max_buflen) % 1 < 0.5 , this PR actually gives you a queue length that's longer and less accurate (by 1) than before the change. For the rest of the situations, this is now more accurate. In sum, this is arguably better because it errs on the more conservative side (larger queue).
I started off using std::max(1, {old result}), which is closest to preserving old behaviour and just catching this error case, but it's probably a bit heavy to `#include<algorithm>` for such a …
> Force max_buflen * srate to be at least 1

- src/stream_inlet_impl.h
- src/time_postprocessor.cpp
- src/time_postprocessor.h
- testing/CMakeLists.txt
- testing/internal/postproc.cpp
- testing/test_ext_DataType.cpp
PR for #117.
- Commit 1: add unit tests for postprocessing options
- Commit 2: Move out smoothing parameters and smoothing code into a separate class that can be re-initialized and tested easier
- Commit 3: reset postprocessing options when `set_options()` is called
- Commit 4: adjust samples_seen when flushing samples
There's one major changes: the number of encountered samples is only tracked while `proc_dejitter` is active. Previously, samples were counted and enabling dejittering afterwards re-used this sample counter and therefore assumed a larger number of timestamps had been used to update the dejittering parameters.
> Reset smoothing parameters after disabling postprocessing

- CHANGELOG
- include/lsl_cpp.h
- testing/test_ext_move.cpp
As of now, each LSL C++ API class keeps a pointer to an opaque LSL object and calls a function (e.g. `lsl_destroy_outlet`) to deconstruct and deallocate the object in its own destructor.
This PR replaces the bare pointers with smart pointers so the compiler can keep track of the C API object lifetimes and generate copy and move constructors / assignment operators automatically.
Moreover, this makes it possible to pass the pointer to end users e.g. for calling C API functions and keep multiple copies of wrapper classes around:
``` cpp
std::shared_ptr<lsl::stream_outlet> raw_handle = stream_outlet(…).get_raw_handle();
// here, the stream outlet is already deconstructed, but the handle is still valid
lsl_push_foo(raw_handle.get());
auto outlet = stream_outlet(...);
auto outlet_copy = outlet; …
```
> C++ API: replace bare pointer with smart pointers.

- include/lsl_cpp.h
I recently had a situation where I had to push some non-zero terminated strings with known lengths to an outlet with a regular sampling rate, so I only had one timestamp.
The C API had `int32_t lsl_push_chunk_buft(lsl_outlet out, const char **data, const uint32_t *lengths, unsigned long data_elements, double timestamp)`, but it wasn't wrapped in the C++ API and I didn't want to give up the niceties the C++ API offered.
This PR adds a function `raw_lsl_ptr` to both the stream outlet and inlet so the plain C API functions can be called without having to rewrite everything to use the C API.
> Add C++ API function to retrieve the opaque C API handles

- .github/workflows/cppcmake.yml
Binaries produced by the preinstalled toolchain depend on `libgcc_s1` which isn't in the default repositories (many thanks to @tobiasherzke for the detailed explanation in #129).
This PR adds a config field `docker` that, when set, runs all steps in this container. For Ubuntu 18.04 builds, it selects the `ubuntu-latest` build image and then runs the rest of the build in the `ubuntu:18.04` docker container. This is less flexible than @tobiasherzke's approach, but requires only minimal changes to the CI config and is ~4x faster.
> Remove Ubuntu 16.04, migrate Ubuntu 18.04 to docker builds.

- CMakeLists.txt
- lslboost/serialization_objects.cpp
- src/portable_archive/portable_archive_exception.hpp
- src/portable_archive/portable_iarchive.hpp
- src/portable_archive/portable_oarchive.hpp
- src/portable_archive/slimarchive.hpp
- testing/internal/serialization_v100.cpp
After replacing large parts of Boost with the C++11 stdlib, there are only (optionally) parts of Asio and Boost.Archive left to build for the boost subset we use, so I've created a single-header header-only shim that offers all of the needed functionality.
It reduces the (release) binary size by 3.4%, build times by ~5% and the dependency on separate Boost compilation units by 100%. I haven'tr tried it, but this could enable building against a system boost installation without name mangling.
Backwards compatibility is a big concern, so [the already existing unit test](https://github.com/sccn/liblsl/blob/master/testing/internal/serialization_v100.cpp) makes sure that both Boost.Archive and the shim here serialize test data and LSL samples with the test pattern to the exact same binary data …
> Header-only shim for Boost.Archive

- CMakeLists.txt
As of 70c001868c6ece914e5ec89d7c8690217bddba05, the Windows builds shouldn't depend on `bcrypt` any more.
As far as I know, @chausner @tobiasherzke are most likely to find a niche compiler on Windows that still needs it. It's not urgent at all, but if you could check it, it'd be great.
> CMake: remove now unneeded bcrypt from link libraries

- .github/workflows/mingw_static.yml
- CMakeLists.txt
For shared builds, the linker combines all object files and CMake discards the private properties of the `lslboost` and `lslobj` targets.
For shared libraries, it just combines the object files and adds references to the interface properties of the two object libraries, so they need to be imported.
Copying the properties manually is messy and error-prone, so this PR adds the two object libraries to the export this. Hopefully fixes #138.
> CMake: add object libraries to the export set for static builds

- src/sample.cpp
- src/sample.h
- testing/test_int_samples.cpp
A sample has a `char*` array to store the values, but the size and type isn't known at compile time.
The values are iterated over in a cast-happy C++98 for-loop: `for (std::string *p = (std::string *)&data_, *e = p + num_channels_; p < e; ++p)`. Also, sample data can be copied in / out in formats different from the native sample format.
In order to simplify the code, this PR adds a helper class and helper methods, so `for (std::string *p = (std::string *)&data_, *e = p + num_channels_; p < e; ++p) { *p = …; }` becomes `for (auto &val : samplevals<std::string>(*this)) { val = …;}`. It also adds two methods: `conv_from(T* src)` copies the values (converting types if necessary) into the sample data, `conv_into(T* dst)` copies the sample data into `dst` (again, converting the types if …
> Move sample copying/conversion to sample.cpp, use template overloading

- CMakeLists.txt
Having a "soname" that stays constant allows compiled
executables that link against liblsl to continue to work
whithout recompilation when liblsl is updated as long as
the soname of liblsl stays the same.
Each time the ABI of liblsl changes in future, the setting
LSL_ABI_VERSION in CMakeLists.txt should be incremented by
one to change the soname.  Closes #140.
> Introduce soname to indicate ABI version of shared library

- src/api_config.cpp
- src/api_config.h
- src/tcp_server.cpp
This allows setting the TCP socket buffer sizes via lsl_api.cfg
I think the default socket buffer size is different on every platform so instead of assuming a default I just set the default to `0` then only update the socket with the API value if it's larger than 0.
> Added socket buffer size options to api_config

- src/socket_utils.cpp
When all configured ports are bound and `allow_random_ports` is enabled, liblsl can try random ports to bind a socket to a port outside the configured range.
This PR changes the socket binding code to open port 0, i.e. let the OS find an open port or abort immediately if there's no free port or no interface to bind to (e.g. as seen in #45).
> `allow_random_ports`: Let the OS choose an open port

- src/tcp_server.cpp
The size of `std::string` is implementation-defined but not relevant for protocol version 110. A size mismatch is therefore not a reason to downgrade the data protocol to 100.
> Fix accidental protocol downgrade

- CMakeLists.txt
- src/data_receiver.cpp
- src/sample.cpp
- src/sample.h
- src/socket_utils.cpp
- src/socket_utils.h
- src/tcp_server.cpp
- src/util/endian.cpp
- src/util/endian.hpp
- testing/ext/DataType.cpp
This PR contains four improvements to endianness operations:
- Move endianness detection / helpers to utils/endian.hpp
Endianness checks / conversions are gathered in one place
- Only store if endianness should be swapped, not the desired endianness. As Boost.Endian only supports swapping between little and big endian, this makes the code a bit easier to read and reason about.
- Pre-compute endian conversion performance once
The endian conversion performance is measured only first time it is requested, speeding up the connection handshake by 10ms.
- Optimize single-byte writes/reads
Reading / writing single bytes uses `streambuf::sbumpc()` and `streambuf::sgetc()` instead of reading/writing buffers of length one. It also makes the code a bit shorter by omitting the `reverse_byte_order` …
> Optimize endianness operations

- include/lsl_cpp.h
- src/resolve_attempt_udp.cpp
- src/resolve_attempt_udp.h
- src/resolver_impl.cpp
- src/resolver_impl.h
This PR includes two improvements to the resolver.
8eec428 raises exceptions for some documented invalid operations:
``` cpp
lsl::resolver_impl resolver;
resolver.results(); // throws, no resolve started so far
resolver.resolve_continuous(…); // ok
resolver.resolve_oneshot(); // throws, continuous resolution in progress
resolver.resolve_continuous(…); // throws, continuous resolution in progress
```
b7af329 speeds up stream resolution by up to `multicast_min_rtt`. By default, `resolver_impl::resolve_oneshot()` sends query packets, waits for results and checks if enough streams have been found whenever a new round of query packets is sent (once ever `multicast_min_rtt` seconds, 0.5 by default. b7af329 checks the completion criteria every time a new stream has been found so stream …
> Two minor stream resolution improvements

- src/consumer_queue.cpp
- src/consumer_queue.h
alignas(64) wasn't supported at all for dynamically allocated memory (<C++17), leading to compiler warnings (#142) and undefined behavior according to the Clang UBSan.
Instead, reorder the fields and insert additional padding (if needed) between fields that shouldn't share a cacheline.
> Rework alignment in consumer_queue

- src/stream_info_impl.cpp
- src/time_postprocessor.cpp
This fixes the following warning with MSVC:
> ...\src\time_postprocessor.cpp(7,9): warning C4068: Unknown pragma "GCC".
Before this change, this pragma was active when compiling with clang. I am not sure if this was on purpose and whether it has any effect on clang. If yes, I can change the condition to:
```c++
if defined(__GNUC__) || defined(__clang__)
```
It also fixes another minor implicit conversion warning.
> Fix two MSVC warnings

- .github/workflows/cppcmake.yml
- src/api_config.cpp
- src/api_config.h
- src/resolve_attempt_udp.cpp
- src/resolve_attempt_udp.h
- src/resolver_impl.cpp
- src/stream_outlet_impl.cpp
- src/udp_server.cpp
- src/udp_server.h
- src/util/cast.cpp
- testing/int/network.cpp
- testing/lslcfgs/default.cfg
- testing/lslcfgs/ipv4_lsl100.cfg
- testing/lslcfgs/ipv4only.cfg
- testing/lslcfgs/ipv6_lsl100.cfg
- testing/lslcfgs/ipv6only.cfg
There have been some more bug reports with streams no / only one stream being found.
Currently, the "I'm looking for a stream"-multicast packets are only sent on one network adapter (on Linux it can be configured otherwise manually, but it ought to work out of the box).
So, this PR adds another config option for all local adapters multicast packets should be sent from, in case it's empty it's generated automatically (currently not yet working on Windows and not tested locally on macOS, but the previously failing CI is happy) and sends the multicast packets once for each configured adapter.
> Send multicast requests on all adapters

- .github/workflows/mingw_static.yml
MinGW build on Github Actions Windows Server 2022 runner failed because CMake was not found in PATH from MSYS2 shell.
CMake is found in Github Actions Windows Server 2019 runner.
For MinGW compilation, exact OS version of the build host is irrelevant.
> Build MinGW on Windows server 2019

- README.md
Now that liblsl is available on Conan Center, I suggest to add a note about package managers to the README.md.
> Add note to README.md about package managers

- .github/workflows/cppcmake.yml
Ubuntu 22.04 will be released next month. It is unclear when github actions will add an ubuntu-22.04 runner.
This is just a suggestion how you could already now build and test your future 1.16 release for Ubuntu 22.04.
BTW you have random failures in one of your unit tests: 
```
install/bin/lsl_test_exported --order rand --wait-for-keypress never --durations yes
5892 Segmentation fault      (core dumped) install/bin/lsl_test_exported --order rand --wait-for-keypress never --durations yes
```
I had this once affect the 18.04 build while the 20.04 build succeeded and once the other way round. I mention this here because this may also fail randomly in the builds triggered by this pull request.
> Add build for upcoming Ubuntu LTS 22.04

- src/api_config.cpp
Loading the log settings last causes heaps of INFO messages to be
displayed by lsl::get_local_interfaces() even if the user has set log level to -3.
Changing the order causes less ui clutter and respects the users choices.
> Load log settings before all other settings.

- thirdparty/loguru/loguru.cpp
Not yet tested on a live device, but compiles against the latest NDK.
> Add pthread_getname_np implementation for NDKs missing it

- src/inlet_connection.cpp
- src/inlet_connection.h
- src/time_receiver.cpp
- src/time_receiver.h
- src/util/cast.cpp
See https://github.com/sccn/labstreaminglayer/issues/105
> Fix recovery issues

- .github/workflows/cppcmake.yml
- .github/workflows/mingw_static.yml
Hopefully this stops a single push to a pull request from double-running workflows.
In my other branch, it didn't seem to help. Maybe it only works if it's already on master? (there are some weird GHA things like that)
> Add concurrency cancellation to GHA workflows.

- include/lsl_cpp.h
Fix buffer size calculation in resolve_streams and resolve_stream functions.
`sizeof(buffer)` returns the byte size of buffer, not the number of elements it contains. This should be modified to `sizeof(buffer) / sizeof(lsl_streaminfo)`.
> Fix buffer size calculation in resolve_streams

- src/portable_archive/portable_iarchive.hpp
- src/sample.cpp
This PR makes two minor changes:
- Add a error message to `static_assert` calls
- replace the singular instance of `std::is_integral_v<T>` with `std::is_integral<T>::value`
These changes do not impact anything else, but make it compatible with C++14 standard.
**Why?**
With this change, I have successfully compiled and tested my Dart api wrapper on `ARMv7` (BELA / BeagleBone black).
SBC/Embedded devices are often running older / restricted hardware, and the BELA runs a variant of Debian 9 (Stretch). This means the compilers are outdated, and the latest available Clang / LLVM is version 7, and the highest C/CPP version available is 14.
> Allow liblsl compilation with c++14.
